include: #incorate their content into this docker-compose
  - DiSA-backend/paperless-ngx/docker-compose.yml

services:
  backend:
    container_name: disa-backend
    build:
        context: .
        dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
    networks:
        app_net:
            ipv4_address: 192.168.2.3

  frontend:
    restart: unless-stopped
    container_name: disa-frontend
    build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
    ports:
        # - "80:80"
        # - "443:443"
        - "5000:80"
    volumes:
        - ./docker/nginx/dev/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - backend
    networks:
        app_net:
            ipv4_address: 192.168.2.2


networks:
    app_net:
        ipam:
            driver: default
            config:
                -   subnet: "192.168.2.0/24"
                    gateway: 192.168.2.1
